name: List Repositories in README

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  list-repos:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Get Repositories from the organization
        id: get_repos
        run: |
          # Replace with your organization name
          ORG_NAME="Pratishthan"
          
          # Fetch all repository names in the organization
          REPOS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/orgs/$ORG_NAME/repos?per_page=100" | \
            jq -r '.[].name')

          echo "::set-output name=repos::$(echo "$REPOS" | tr '\n' ' ')"

      - name: Generate Index for README
        run: |
          # Fetch the repositories
          REPOS="${{ steps.get_repos.outputs.repos }}"
          
          # Start the markdown content for the index
          INDEX_CONTENT="# List of Repositories\n\n"

          # Loop through repositories and create the markdown list
          for REPO in $REPOS; do
            INDEX_CONTENT="$INDEX_CONTENT- [$REPO](https://github.com/Pratishthan/$REPO)\n"
          done

          # Append the content to the README file
          echo "$INDEX_CONTENT" > README.md

      - name: Commit the updated README
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add README.md
          git commit -m "Update repository index in README"
          git push
