name: List Files in README (Exclude README, .git, and Workflow Files)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  list-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: List all files (excluding README.md, .git, .github, LICENSE)
        id: list_files
        run: |
          echo "index_content<<EOF" >> $GITHUB_OUTPUT

          echo "# File Index" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT

          find . -type f \
            ! -name 'README.md' \
            ! -name 'LICENSE' \
            ! -path './.git/*' \
            ! -path './.github/*' |
          while read FILE; do
            ESCAPED=$(echo "$FILE" | sed 's/ /%20/g' | sed 's|^\./||')
            echo "- [$ESCAPED]($ESCAPED)" >> $GITHUB_OUTPUT
          done

          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update README with File Index
        run: |
          echo "# org-learning-resources" > README.md
          echo "" >> README.md
          echo "${{ steps.list_files.outputs.index_content }}" >> README.md

      - name: Commit and Push Updated README
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "Update file index in README"
          git push
