name: List Files in README (Exclude README, .git, and Workflow Files)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  list-files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: List all files in the repository (excluding README.md, .git, and workflows)
        id: list_files
        run: |
          # List all files in the repository, excluding README.md, .git, and .github/workflows
          FILES=$(find . -type f ! -name 'README.md' ! -path './.git/*' ! -path './.github/*')

          # Create an initial index for the README file
          INDEX_CONTENT="# File Index\n\n"

          # Loop through the files and create a markdown list
          for FILE in $FILES; do
            # Escape spaces in file names for markdown compatibility
            FILE_NAME=$(echo $FILE | sed 's/ /%20/g')
            INDEX_CONTENT="$INDEX_CONTENT- [$FILE_NAME]($FILE)\n"
          done

          # Set output for the index content
          echo "::set-output name=index_content::$INDEX_CONTENT"

      - name: Update README with File Index
        run: |
          # Fetch the index content
          INDEX_CONTENT="${{ steps.list_files.outputs.index_content }}"

          # Append the content to the README file
          echo "$INDEX_CONTENT" > README.md

      - name: Commit the updated README
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add README.md
          git commit -m "Update file index in README"
          git push
